### ISSUE TITLE
Video preprocessing

### ISSUE THREAD

**Issue by mcomunita** [XYPB/CondFoleyGen#4]
Hi!

I noticed that there are two video_preprocessing scripts:
`video_preprocessing.py`
and
`feature_extraction/video_preprocessing.py`

which both seem to do resizing of the video and resampling of the audio, but only the first is denoising the audio, while the second extracts the video frames.

Could you help me understand which preprocessing you used for training?

Thanks

**Comment by XYPB** [comment]
Thank you again for the issue. A quick answer is that you should use `feature_extraction/video_preprocessing.py` to preprocess the video for training since it provides the correct data structure as needed for training.

Meanwhile, `video_preprocessing.py` is used to preprocess single videos that will be used for demonstration and generation.

We have just updated the `--denoise` flag for `feature_extraction/video_preprocessing.py` so that you can generate the denoised audio at the same time under the correct training data folder.

**Comment by mcomunita** [comment]
Great! Thanks for the clarification and the update
