### ISSUE TITLE
frame_resize.jpg

### ISSUE THREAD

**Issue by Yusiissy** [XYPB/CondFoleyGen#6]
Thanks for your great open source work！
I'm having two problems with the data while training the model and would like to get a reply from you.

1.When I run the second stage training code, the error is reported as:

FileNotFoundError: [Errno 2] No such file or directory: 'data/greatesthit/greatesthit_processed/2015-03-25-01-07-20/frames/frame000110_resize.jpg'

Then I noticed that the 672L,708L,883L，in /specvqgan/data/greatesthit.py .The frame_resize.jpg file is required for data reading, how do I get this file, I didn't find information about it in the data preprocessing code.

looking forward to your reply!
```
   # target
        wave_path = self.video_audio_path[video]
        frames = [Image.open(os.path.join(
            frame_path, f'frame{i+1:0>6d}_resize.jpg')).convert('RGB') for i in
            range(start_frame_idx, end_frame_idx)]
        wav, sr = soundfile.read(wave_path, frames=int(SR * self.L), start=start_idx)
        assert sr == SR
        wav = self.wav_transforms(wav)
```
2.Also in data reading, the reading is audio/{v}_denoised_resampled.wav, and according to the data processing code /feature_extraction/video_preprocess.py it is resampling and then noise reduction, and the final result is audio/{v}_resampled_denoised.wav. 
which is the correct processing order?

619L， /specvqgan/data/greatesthit.py
`self.video_audio_path = {v: os.path.join(self.data_path, v, f'audio/{v}_resampled_denoised.wav') for v in video_name}`

**Comment by XYPB** [comment]
Thanks for your post!

1. This is actually a bug in the released code, the current pre-processing script in `./feature_extraction/video_preprocess.py` already resized the frame to a smaller as desired. The code that loads frames with `f'frame{i+1:0>6d}_resize.jpg'` was used under the experimental machine, which should not have `_resize` string in this version. We have fixed this issue so that you don't need `*_resize.jpg` anymore, and you can load from normal images processed by the provided script directly.
2. The `_denoised` flag for the Greatest Hits dataset actually refers to the originally denoised input video, rather than the denoise in the `./feature_extraction/video_preprocess.py` script. This is to say, you don't need the `--denoise flag for the Greatest Hits dataset when running pre-processing, instead, you need directly load input videos with `_denoised.mp4` ending. We have fixed this issue right now, and you only need to run `./feature_extraction/video_preprocess.py` with `--greatesthit` flag, and it will then generate correct wave files ending with `_denoised.wav` and `_denoised_resampled.wav`.

We apologize for the confusion due to these issues. Hope this reply and the corresponding update can help address your question.

**Comment by Yusiissy** [comment]
Thank you for the reply and update, that solved my problem nicely!
