### ISSUE TITLE
Countix AV onsets

### ISSUE THREAD

**Issue by riccardofosco95** [XYPB/CondFoleyGen#7]
Hi, can I ask what the data in CountixAV_onsets.json correspond to? Are they the frames at which each onset occurs in the videos of the Countix AV test set? 
If so, how were they derived and what frame rate do they refer to?
Thank you

**Comment by XYPB** [comment]
Thanks for your issue!

Yes, they are the *frames* that the onset occurs in the videos from the Countix AV test set, but it is not the visual frame, but the *audio frame*, in a sampling rate/audio FPS of 22050.

This result was obtained by using the `librosa.onset.onset_detect` function, with the same settings as the onset baseline, which can be found under the `specvqgan/onset_baseline` folder. 

However, we do not recommend you use this file for further evaluation or training since this detection result was not satisfactory according to our experiment. This is mainly due to the complex audio condition in the CountixAV dataset, which makes the librosa library harder to obtain a reasonable onset detection result.

We will remove this file from the repo in case of further confusion.
