### ISSUE TITLE
how to get evaluate metrics

### ISSUE THREAD

**Issue by Yusiissy** [XYPB/CondFoleyGen#9]
hi！

I noticed you created three metrics in your paper：Material Acc/Action Acc/Onset Acc .

And I also noticed evaluate_auto.py ，From the code it looks like it has something to do with the file you get in create_test_folder.py . Also, to execute create_test_folder.py, I need to first execute audio_generation.py

I'm not sure if I'm right in thinking that, can you be generous with the process and specific commands on how to get those three metrics?Thanks, looking forward to a reply!

**Comment by Yusiissy** [comment]
hello! When I run audio_generation.py with the following command：
`python audio_generation.py --gh_testset --model_name 2022-05-03T11-33-05_greatesthit_transformer_with_vNet_randshift_2s_GH_vqgan_no_earlystop  --target_log_dir gh_1`

He got the following error: 
line 47 in `CondFoleyGen/specvqgan/modules/transformer/permuter.py`
`return x[:, self.forward_shuffle_idx]`

/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [54,0,0] Assertion index >= -sizes[i] && index < sizes[i] && "index out of bounds" failed.

when I debugging, I noticed x.shape=[1,50] and len(self.forward_shuffle_idx)=60，I think it got an index overflow.
It seems that the shape of x should be[1,60]

So I try to change the parameter `spec_take_first` of the function `gen_audio_condImage_fast()` to 192 (default 160)
 Programs can run normally.But I don't know if this is the right way to do it, please correct me！！

**Comment by XYPB** [comment]
Hi~

I'm sorry for not getting back to you sooner! Thank you for your amazing issue. 
So for the first question, we have just updated the readme and you should now have access to the process of evaluations. Unfortunately, I have left UMich and currently have no access to the VGG-ishish model weight for the action/material prediction. But we still have the corresponding config file and you may still train the model by yourself, which should be pretty quick.

For the second question. yes, you are correct! This is because the old model was trained in the full spectrogram of width 192 rather than a 2-sec wave, which can only result in a spectrogram of size 160. Thus, the old model (2022-05-03T11-33-05_greatesthit_transformer_with_vNet_randshift_2s_GH_vqgan_no_earlystop) needs a larger token sequence length (60 rather than 50).

Thank you for the question! Hope this can help~

Yuexi

**Comment by Yusiissy** [comment]
Thanks for your prompt reply, I am now trying to pre-train a VGG-ishish model！
in the vggish_gh.yaml 
`mels_path: '/home/duyxxd/SpecVQGAN/data/greatesthit/melspec_10s_22050hz'`
I would like to know how I can get the` melspec_10s_22050hz `folder for the gh dataset.
Do I need to process the data, can you tell me the code to do that?
Also,during training of the model, `meta_path='/home/duyxxd/SpecVQGAN/data/info_r2plus1d_dim1024_15fps.json`' is required for data reading，I can only find `greatest_hit_meta_info.tar.gz` which seems to be related to this

**Comment by XYPB** [comment]
To extract the melspec_10s_22050hz feature, you may use `./feature_extraction/extract_mel_spectrogram_greatesthit.py`, which will create the `melspec_10s_22050hz` folder. 

As for the `info_r2plus1d_dim1024_15fps.json`, we have just uploaded it to the `data` folder, which you may use directly!

**Comment by Yusiissy** [comment]
Sorry I forgot to close the question, thanks again for your help!
